"""empty message

Revision ID: 1a5e146a84cc
Revises: fa02a057ea2f
Create Date: 2020-08-31 14:23:07.517098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5e146a84cc'
down_revision = 'fa02a057ea2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=True)
    # ### end Alembic commands ###
