"""empty message

Revision ID: 2a11772bba6c
Revises: 1a5e146a84cc
Create Date: 2020-08-31 14:27:01.323432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a11772bba6c'
down_revision = '1a5e146a84cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('name', 'user', ['name'], unique=True)
    # ### end Alembic commands ###
