"""empty message

Revision ID: 74d6db44c4fc
Revises: 2a11772bba6c
Create Date: 2020-09-01 09:27:32.256067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d6db44c4fc'
down_revision = '2a11772bba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='social')
    op.drop_index('username', table_name='social')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'social', ['username'], unique=True)
    op.create_index('email', 'social', ['email'], unique=True)
    # ### end Alembic commands ###
