"""empty message

Revision ID: 84f18be8eb5e
Revises: 74d6db44c4fc
Create Date: 2020-09-01 12:49:17.235452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f18be8eb5e'
down_revision = '74d6db44c4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multimedia', sa.Column('multimedia_type', sa.Enum('img', 'video', name='multimediaenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multimedia', 'multimedia_type')
    # ### end Alembic commands ###
