"""empty message

Revision ID: d51c0b281ae8
Revises: ff1f69f611d3
Create Date: 2020-09-20 16:31:32.284383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51c0b281ae8'
down_revision = 'ff1f69f611d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('publication', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'publication')
    # ### end Alembic commands ###
