"""empty message

Revision ID: fa02a057ea2f
Revises: 7d97acf7109f
Create Date: 2020-08-31 13:06:36.971557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02a057ea2f'
down_revision = '7d97acf7109f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'social', ['username'])
    op.create_unique_constraint(None, 'social', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social', type_='unique')
    op.drop_constraint(None, 'social', type_='unique')
    # ### end Alembic commands ###
